# Generated by Django 5.2.7 on 2025-10-26 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='award',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
        migrations.AddField(
            model_name='activitygoal',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
        migrations.AddField(
            model_name='points',
            name='award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.award'),
        ),
        migrations.AddField(
            model_name='points',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.activitygoal'),
        ),
        migrations.AddField(
            model_name='points',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout'),
        ),
        migrations.AddField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
        migrations.AddConstraint(
            model_name='points',
            constraint=models.UniqueConstraint(fields=('goal', 'award', 'workout'), name='unique_goal_award_workout'),
        ),
    ]
