# Generated by Django 5.2.7 on 2025-10-26 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('Steps', 'Total Daily Steps'), ('Badminton', 'Badminton'), ('Ride', 'Biking/Cycling'), ('EBikeRide', 'Biking/Cycling (E-Bike)'), ('GravelRide', 'Biking/Cycling (Gravel)'), ('Handcycle', 'Biking/Cycling (Handcycle)'), ('Velomobile', 'Biking/Cycling (Velomobile)'), ('VirtualRide', 'Biking/Cycling (Virtual)'), ('Canoeing', 'Canoe'), ('Crossfit', 'Crossfit'), ('Elliptical', 'Elliptical'), ('Golf', 'Golf'), ('HighIntensityIntervalTraining', 'High Intensity Interval Training (HIIT)'), ('Hike', 'Hike'), ('IceSkate', 'Ice Skate'), ('InlineSkate', 'Inline Skate'), ('Kayaking', 'Kayak'), ('Kitesurf', 'Kitesurf'), ('MountainBikeRide', 'Mountain-Biking/Cycling'), ('EMountainBikeRide', 'Mountain-Biking/Cycling (E-Bike)'), ('Pickleball', 'Pickleball'), ('Pilates', 'Pilates'), ('Racquetball', 'Racquetball'), ('RockClimbing', 'Rock Climbing'), ('Rowing', 'Rowing (Outdoor)'), ('VirtualRow', 'Rowing (Virtual)'), ('Run', 'Run'), ('TrailRun', 'Run (Trail)'), ('VirtualRun', 'Run (Treadmill / Vitual)'), ('Sail', 'Sail'), ('Skateboard', 'Skateboard'), ('AlpineSki', 'Ski (Alpine)'), ('BackcountrySki', 'Ski (Backcountry)'), ('NordicSki', 'Ski (Nordic)'), ('RollerSki', 'Ski (Roller/Inliner)'), ('Snowboard', 'Snowboard'), ('Soccer', 'Soccer / Football'), ('Squash', 'Squash'), ('StairStepper', 'Stair Stepper'), ('StandUpPaddling', 'Stand-up Paddling'), ('Surfing', 'Surf'), ('Swim', 'Swim'), ('TableTennis', 'Table Tennis'), ('Tennis', 'Tennis'), ('Walk', 'Walk'), ('Snowshoe', 'Walk (Snowshoe)'), ('WeightTraining', 'Weight Training'), ('Wheelchair', 'Wheelchair'), ('Windsurf', 'Windsurf'), ('Yoga', 'Yoga'), ('Workout', 'Other Workout')], max_length=40)),
                ('start_datetime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('intensity_category', models.IntegerField(choices=[(1, 'Easy (Could do another one later today)'), (2, 'Moderate (Done for today but tomorrow is a new day)'), (3, 'Hard (Will definitely feel this workout tomorrow)'), (4, "All Out (Can't do another one tomorrow)")], null=True)),
                ('kcal', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('steps', models.IntegerField(null=True)),
                ('strava_id', models.BigIntegerField(null=True, unique=True)),
                ('strava_intensity_avg_watts', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
